name: build-wasm
run-name: ${{ github.actor }} is building wasm file. guimods ${{ github.event.inputs.guimods_tag }} + gui-v2 ${{ github.event.inputs.gui_v2_tag }}

on:
    workflow_dispatch:
      inputs:
        gui_v2_repository:
          description: "Repository override for gui-v2"
          type: string
          #default: victronenergy/gui-v2
        gui_v2_tag:
          description: "Ref to build on github.com/victronenergy/gui-v2"
          required: true
          type: string
          default: refs/heads/main #refs/tags/v1.1.30
        guimods_apply:
          description: "Whether to apply guimods from github.com/Sarah-1331/guimods"
          required: true
          type: boolean
          default: false
        guimods_tag:
          description: "Ref to use on github.com/Sarah-1331/guimods"
          required: true
          type: string
          default: refs/heads/main

  # push:
  #   paths-ignore:
  #     - '**/README.md'

jobs:
  build-wasm-file:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        id: gui_v2_checkout
        with:
          submodules: recursive
          repository: ${{ github.event.inputs.gui_v2_repository }}
          ref: ${{ github.event.inputs.gui_v2_tag }}

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        id: guimods_checkout
        if: ${{ github.event.inputs.guimods_apply == 'true' }}
        with:
          path: guimods
          repository: Sarah-1331/guimods
          ref: ${{ github.event.inputs.guimods_tag }}

      - name: Apply guimods
        if: ${{ github.event.inputs.guimods_apply == 'true' }}
        shell: bash
        run: |
          # Fake /opt/victronenergy/gui-v2/Victron/VenusOS/components/widgets
          mkdir -p /opt/victronenergy/gui-v2/Victron/VenusOS
          ln -s $(readlink -f components) /opt/victronenergy/gui-v2/Victron/VenusOS/components

          # Fake reboot
          reboot () { echo "Reboot called (ignored)" ; }

          # Apply
          cd guimods
          . ./install_widgets.sh

      - name: Set up environment variables from "scripts/.env" file
        run: |
          if [ -f "scripts/.env" ]; then
              export $(grep -v '^#' "scripts/.env" | xargs)
          else
              echo "## scripts/.env file not found!"
              exit 1
          fi
          echo "EMSCRIPTEN=$EMSCRIPTEN" >> $GITHUB_ENV
          echo "QT_VERSION=$QT_VERSION" >> $GITHUB_ENV
          echo "OUTPUTDIR=$OUTPUTDIR" >> $GITHUB_ENV

      - name: Show fetched environment variables
        run: |
          echo "Loaded environment variables from \"scripts/.env\" file:"
          echo "EMSCRIPTEN: ${{ env.EMSCRIPTEN }}"
          echo "QT_VERSION: ${{ env.QT_VERSION }}"
          echo "OUTPUTDIR: ${{ env.OUTPUTDIR }}"

      - name: Check for a cached version
        uses: actions/cache@v4
        id: cached-versions
        with:
          path: |
            # Cache the Qt and emscripten installation
            ${{ env.OUTPUTDIR }}
          # Adding version as cache key
          key: ${{ runner.os }}__qt-${{ env.QT_VERSION }}__em-${{ env.EMSCRIPTEN }}__libegl1

      - name: Install requirements (cache miss)
        if: steps.cached-versions.outputs.cache-hit != 'true'
        run: |
          bash scripts/build-wasm-install-requirements.sh

      - name: Install libraries needed for building the wasm (cache hit)
        if: steps.cached-versions.outputs.cache-hit == 'true'
        run: |
          sudo apt-get update -yq
          sudo apt-get install -y libegl1

      - name: Build WebAssembly
        run: |
          bash scripts/build-wasm.sh

      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: venus-webassembly
          path: build-wasm_files_to_copy
          retention-days: 5

      - name: Release - ZIP wasm files
        if: false
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd build-wasm_files_to_copy
          zip -r ../venus-webassembly.zip wasm

      - name: Release - Create release with wasm files
        if: false
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: venus-webassembly.zip
          name: guimods ${{ steps.guimods_checkout.outputs.commit }} + gui-v2 ${{ steps.gui_v2_checkout.outputs.ref }} (${{ steps.guimods_checkout.outputs.commit }})